### ISSUE TITLE
Keep all versions of site live

### ISSUE THREAD

**Issue by sidvishnoi** [csdu/sankalan-2019#1]
It would be nice if we can keep all past year website versions on site, instead of overriding them. Although it adds a little maintenance burden, but we can view how we have evolved our websites each year. Also useful if the developers want to reference their work.
So, we can have folders like this which contain entire website for that year:
``` bash
/sankalan/                 # for latest/current year
/sankalan/2018/            # year wise
```
What would remain each year is just to change the build script paths each year and we would just need to deploy the old site once on gh-pages.

**Comment by rumansaleem** [comment]
Yeah! it is one of the pending tasks. We will soon add older version as well. :slightly_smiling_face:

**Comment by sidvishnoi** [comment]
@rumansaleem any update on this? I would like to make this visible to public (for portfolio). Or should I self-host it?

**Comment by jatin69** [comment]
@sidvishnoi hey man, we've been really occupied lately with all the assignments, projects. Didn't get the time to deal with it yet. Last time @rumansaleem and I talked about this, the priority was to get the current site moved to github. So ya, this still needs to be done.

Although, if you are asking for portfolio reasons, it still makes sense to host it on your github as well.

**Comment by sidvishnoi** [comment]
I would've to rebuild and change the URLs 😅 
Anyway, temporarily hosted at http://jealous-polish.surge.sh/sankalan/2018/
Please make it live on ducs.in domain whenever possible, as it's more stable.

**Comment by rumansaleem** [comment]
Hey @sidvishnoi! apologies for being too late in resolving the matter. :sweat_smile:

Finally, We have deployed the older version build at https://ducs.in/sankalan-2018. We have forked your repository and served it using GitHub Pages with [gh-pages](https://github.com/csdu/sankalan-2018/tree/gh-pages) branch.

**Comment by sidvishnoi** [comment]
Thanks! 🎉

**Comment by jatin69** [comment]
@rumansaleem If it's not too much trouble, I'd also insist on moving sankalan 2019 as well to  [https://ducs.in/sankalan-2019](https://ducs.in/sankalan-2019) and set [https://ducs.in/sankalan/](https://ducs.in/sankalan/) to a coming soon page.

**Comment by rumansaleem** [comment]
Yea sure. I will do it as soon as we start the work for 2020.
